### ISSUE TITLE
Features of The Noble Quran should develop

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#1]
what features of the noble Quran should we develop and include in the application, list down to see the future features.

**Comment by MidtorJya** [comment]
Future Features in noble quran
-Translate when point(word byword)
-Play when click(word by word)
-Choose Languages using in web app
-Resize front
-Choose reciter
-Select languages meaning
-Seperate by surah
-Seperate bu Juz
-Highlight word when play
-Search button
-Select verse
-Tafsir
_Tajweed

**Comment by marymarywan** [comment]
**The Features that the Noble Quran website might need** 
- Search by ( Surah, Verses, Parts )
- Dark mode or Reading mode 
- Group filter ( Madani or Makki , Group of Tajweed  )
- Share board - for community sharing

**Comment by Katlovepickle** [comment]
https://docs.google.com/presentation/d/1A-xFNvkImIszNr8EOi_CTU8pBvsLpYEHjzF-675mn0c/edit?usp=sharing

- Search Engine
- Quran Display, Categorized by Juz, place and etc
- UI Language Selection
-  Feedback ,Announcement
- Surah info , context, and theme
-  Read mode, UI color changes, font resizing

-

**Comment by rofikcroft** [comment]
[https://classroom.google.com/u/0/c/MTM3NDExMzM4OTQz](url)
*Quran Audio*
-play by verse (ayah)
-play by chapter (surah)
-read fast or slow
-select reader (Qari) of choice
-read with translation
   -select language

**Comment by NihengMae** [comment]
[Quran online.pdf](https://github.com/langsari/the-noble-quran/files/5212205/Quran.online.pdf)

-Translation support more languages
-Transliteration support more languages
-99 names God high line
-Tajwid high line and the mane of each Tajwid 
-Teaching Tajwid and correct pronunciations
-Select the story that related with that Ayah

**Comment by MUKHLIS575** [comment]
[Ayat Al-quran.pdf](https://github.com/langsari/the-noble-quran/files/5215671/Ayat.Al-quran.pdf)

Search by ( Surah, Verses, pages, juzz )
Translation support more languages
Quran Audio( play by verse, play by chapter)
select reader (Qari) of choice
Share board - for community sharing

Mukhlis Meeraya 601431003

**Comment by arrushchai03** [comment]
[QuranOnline.net.pptx](https://github.com/langsari/the-noble-quran/files/5215725/QuranOnline.net.pptx)

•Search surah, meaning, history, reading 
•Surah info
•Translation 7 language 
•Reading English language 
•Select reciter
•Play audio

Arrush Chaimass 611431014

**Comment by cheloh** [comment]
[Islamicfinder - Modern Language (presentation).pdf](https://github.com/langsari/the-noble-quran/files/5215756/Islamicfinder.-.Modern.Language.presentation.pdf)

- Search by Verses(Ayah), Pages, Juzz, Topic.
- Translation support more languages.
- Select reader
- Selection UI Language

**Comment by MoeObaid** [comment]
http://www.surahquran.com
[MODERN LAUNGAGE PROGRAMMING.pptx](https://github.com/langsari/the-noble-quran/files/5215829/MODERN.LAUNGAGE.PROGRAMMING.pptx)

- Quran live radio.
- Download different prints of quran, as a pdf file.
- Listening and download as a mp3.
- Search Engine include surah, topic of verse, and hadeeth.


Husnee Sama       601431021
Mohamed Obaid  611431025

**Comment by Ameen25018** [comment]
[Quran.pptx](https://github.com/langsari/the-noble-quran/files/5224957/Quran.pptx)

Category
-Quran
-Tafseer
-Language
-Book

**Comment by langsari** [comment]
As our discussion, features of The Noble Quran Web Application should develop as the following;
API #3 
Content #4 
Application Language #7 
Audio #8 
CRUD #9 
Database #10 
Quranic #11 
Feedback and Help #19 
Login #15 
Register #16 
Search #6 
Tafsir #17 
Translation #12 
Transliteration #13 
User Interface (UI) and User Experience (UX) #5 
Video #14 
Download
Notification
Quick link
Share
Tajwid

Each feature, there is an open issue addressed.
Discuss and description of what each responsible feature will be designing, developing, and coding.

**Comment by kasang2015** [comment]
https://docs.google.com/presentation/d/1A-xFNvkImIszNr8EOi_CTU8pBvsLpYEHjzF-675mn0c/edit#slide=id.p
Search Engine
Quran Display, Categorized by Juz, place and etc
UI Language Selection
Feedback, Announcement
Surah info, context, and theme
Read mode, UI color changes, font resizing
Audio

arif dorloh 
armeen kasengteuba 631431020

**Comment by Samae99** [comment]
[Ayat-Al-quran.pptx](https://github.com/langsari/the-noble-quran/files/5230257/Ayat-Al-quran.pptx)

- Quran Audio( play by verse, chapter or many chapter) of choice
- search surah ayat 
- Share board - for community sharing
- Dark mode or Reading mode
- video teaching or tafsir quran


Hassan Samae [601431014

**Comment by ilham199917** [comment]
[Islamicfinder-Modern-Language-presentation.pdf](https://github.com/langsari/the-noble-quran/files/5289263/Islamicfinder-Modern-Language-presentation.pdf)

Search by verse surah juz.
Specific word.
Highlight the word when play.
Reader many type.
Dowload Audio.

**Comment by langsari** [comment]
this close #3, close #4
