### ISSUE TITLE
QuranAPI

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#3]
response request queries through Application Programming Interface (API);
API format as REATful or SOAP,
URLs path of API,
design how to response query,
etc.

Feature detail, read, write and describe more in [README.md](https://github.com/langsari/the-noble-quran/blob/master/Modules/QuranAPI/README.md)
and implement in `/Modules/QuranAPI/`

**Comment by kasang2015** [comment]
https://docs.google.com/presentation/d/1A-xFNvkImIszNr8EOi_CTU8pBvsLpYEHjzF-675mn0c/edit#slide=id.p
Search Engine
Quran Display, Categorized by Juz, place and etc
UI Language Selection
Feedback, Announcement
Surah info, context, and theme
Read mode, UI color changes, font resizing
Audio

**Comment by Katlovepickle** [comment]
https://restfulapi.net/
https://restfulapi.net/introduction-to-json/
https://rb.gy/3ucm63

อ่านด้วย

**Comment by kasang2015** [comment]
new slide
https://docs.google.com/presentation/d/1nhlcy9_-PYbxWwdN-lg6BVy6nvYKBznBltkPd26gEQA/edit?usp=sharing

**Comment by kasang2015** [comment]
https://www.patanasongsivilai.com/blog/api-%E0%B9%81%E0%B8%9A%E0%B8%87%E0%B8%84%E0%B9%8C%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%B4/
ตัวอย่าง Code คำสั่ง API

**Comment by Katlovepickle** [comment]
Go read ablout guzzle @kasang2015 .http://docs.guzzlephp.org/en/stable/

**Comment by Katlovepickle** [comment]
https://devahoy.com/blog/2020/02/restful-api-guideline/
https://www.babelcoder.com/blog/articles/rest-api-design

Quick read Guidelines

**Comment by kasang2015** [comment]
https://docs.google.com/presentation/d/1nhlcy9_-PYbxWwdN-lg6BVy6nvYKBznBltkPd26gEQA/edit?usp=sharing
new slide update aboute differen bitween post, put and path

**Comment by langsari** [comment]
These are an example of API what we are looking for;

especially this site : https://quran.api-docs.io/v3/getting-started/introduction 

API
https://quran.api-docs.io/v3/getting-started/introduction
https://api.quranwbw.com/
https://www.helloquran.com/api (English Translation)
https://alquran.cloud/api

FILE
http://tanzil.net/trans/ (Quran Translations)
https://github.com/MEOW119X/Collect-files/tree/main/quran/quran-text (Quran Text txt, xlsx, csv - files)
