### ISSUE TITLE
QuranContent

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#4]
Quran content;
content,
context, 
Surah info, 
font; Resize front,
display, 
text display,
Seperate by surah,
Seperate by Juz,
Select verse
Quran Display, Categorized by Juz, place and etc
Surah info, context, and theme

Feature detail, read, write and describe more in [README.md](https://github.com/langsari/the-noble-quran/blob/master/Modules/QuranContent/README.md)
Implement in `/Module/Content`

**Comment by HossniSama** [comment]
In this feature we just display the content of the quran 
And with Separate by Surah, and Juz. and also how to make the font display as Quran

**Comment by HossniSama** [comment]
so How about the design of the page depend on me? 
or we follow same structure you need?
