### ISSUE TITLE
Quran Search

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#6]
Quran Search Feature; 
Search by keyword, 
Search by meaning, 
Search by surah name, 
etc.

Feature detail, read, write and describe more in [README.md](https://github.com/langsari/the-noble-quran/blob/master/Modules/QuranSearch/README.md)
Implement in `/Modules/QuranSearch/`

**Comment by MidtorJya** [comment]
อาจารย์คะ หนูไปcommit ผิดในbranch master รบกวนอาจารย์ช่วยลบหน่อยค่า อันที่creat juz 1-30 (search by juz)

**Comment by MidtorJya** [comment]
source codeที่เราสร้างให้ใส่ในไฟล์s scr หรือ module/QuranSearch คะ

**Comment by langsari** [comment]
> อาจารย์คะ หนูไปcommit ผิดในbranch master รบกวนอาจารย์ช่วยลบหน่อยค่า อันที่creat juz 1-30 (search by juz)

 เดินหน้าต่อไปครับ

**Comment by langsari** [comment]
> source codeที่เราสร้างให้ใส่ในไฟล์s scr หรือ module/QuranSearch คะ

Commit to your responsible module, in case of your is commit in Module/QuranSearch

**Comment by MidtorJya** [comment]
elasticsearch
https://medium.com/machinereading/elasticsearch-%E0%B8%A0%E0%B8%B2%E0%B8%84%E0%B8%A5%E0%B8%B8%E0%B8%A2%E0%B8%AA%E0%B8%99%E0%B8%B2%E0%B8%A1-%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88-1-19077ab210b3

**Comment by MidtorJya** [comment]
Aslamualaikum,teacher 
I got this error , and I try to solve it many way .But it doesn't work .Can u help me .

**Comment by MidtorJya** [comment]
[QuranSearch 7.10.pdf](https://github.com/langsari/the-noble-quran/files/5342690/QuranSearch.7.10.pdf)

**Comment by MidtorJya** [comment]
Ref
https://www.web-development-blog.com/using-elasticsearch-with-php/

https://packagist.org/packages/elasticsearch/elasticsearch

https://medium.com/i-gear-geek/%E0%B8%9F%E0%B8%B5%E0%B9%80%E0%B8%88%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B9%83%E0%B8%99-elasticsearch-%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B8%87%E0%B8%B2%E0%B8%99-laravel-%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%881-%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B8%9E%E0%B8%B7%E0%B9%89%E0%B8%99%E0%B8%90%E0%B8%B2%E0%B8%99-cbd2d20ecd40

https://medium.com/machinereading/elasticsearch-%E0%B8%A0%E0%B8%B2%E0%B8%84%E0%B8%A5%E0%B8%B8%E0%B8%A2%E0%B8%AA%E0%B8%99%E0%B8%B2%E0%B8%A1-%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88-1-19077ab210b3

https://kb.objectrocket.com/elasticsearch/how-to-create-simple-search-engine-using-elasticsearch-php-client-176#connect+the+php+script+to+the+low-level+elasticsearch+client

**Comment by MidtorJya** [comment]
![122609667_285431442559784_2363987143649748618_n](https://user-images.githubusercontent.com/54342250/97383956-4fd5b780-1901-11eb-8ed8-64e129976228.jpg)

Teacher, If someone merge  branch  AlquanApplicationLaguage with QuranSearch without permission , Make me confuse a  bit .Cloud I create new branch or What should I do . Thanks

**Comment by langsari** [comment]
> ![122609667_285431442559784_2363987143649748618_n](https://user-images.githubusercontent.com/54342250/97383956-4fd5b780-1901-11eb-8ed8-64e129976228.jpg)
> 
> Teacher, If someone merge branch AlquanApplicationLaguage with QuranSearch and there are something wrong , Make me confuse a bit .Cloud I create new branch or What should I do . Thanks

Does the commit effect to your work much? warn to @marymarywan.

@marymarywan Why you do this, please do not tough other people work without permission. 
@marymarywan do not commit to other people working folder, you have got your group folder already #30

**Comment by langsari** [comment]
> > ![122609667_285431442559784_2363987143649748618_n](https://user-images.githubusercontent.com/54342250/97383956-4fd5b780-1901-11eb-8ed8-64e129976228.jpg)
> > Teacher, If someone merge branch AlquanApplicationLaguage with QuranSearch and there are something wrong , Make me confuse a bit .Cloud I create new branch or What should I do . Thanks
> 
> Does the commit affect to your work much? warn to @marymarywan.
> 
> @marymarywan Why you do this, please do not touch other people's work without permission.
> @marymarywan do not commit to other people working folder, you have got your group folder already #30

@MidtorJya  warn to @marymarywan and FIX the conflicted merge. NO NEED to create a new branch, delete all that is not belong to your folder and files.

**Comment by MidtorJya** [comment]
Final result of QuranSearch
(; search by surah-name , word, number and highlight keyword)

Suraiya Thaweenhern 612431012
Nurul-izzah Panae  602431004

vdo : https://www.youtube.com/watch?v=o4U6Fp-Rye0

<img width="1439" alt="Screen Shot 2563-11-20 at 16 09 29" src="https://user-images.githubusercontent.com/54342250/99781904-0ae12180-2b4b-11eb-9c2e-bd2b658f13a9.png">
<img width="1439" alt="Screen Shot 2563-11-20 at 16 09 47" src="https://user-images.githubusercontent.com/54342250/99781915-0ddc1200-2b4b-11eb-9e2d-696e7caa1ded.png">
<img width="1440" alt="Screen Shot 2563-11-20 at 16 10 01" src="https://user-images.githubusercontent.com/54342250/99781920-0f0d3f00-2b4b-11eb-872e-5dfb69ba765c.png">
<img width="1440" alt="Screen Shot 2563-11-20 at 16 10 13" src="https://user-images.githubusercontent.com/54342250/99781923-0fa5d580-2b4b-11eb-9f5e-e2ccb01d1961.png">
