### ISSUE TITLE
Quran Application Language

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#7]
Quran Application Language;
Internationalize language of the application,
etc.

Feature detail, read, write and describe more in [README.md](https://github.com/langsari/the-noble-quran/blob/master/Modules/QuranApplicationLanguage/README.md)

Implement in `/Modules/QuranApplicationLanguage/`

**Comment by marymarywan** [comment]
ใช้ Google translator API ได้มั้ย

**Comment by langsari** [comment]
> ใช้ Google translator API ได้มั้ย

better to create a custom translation corpus for a specific site, 
check this https://symfony.com/doc/current/translation.html

**Comment by marymarywan** [comment]
**This is the method of languages switcher used for websites**
https://blog.weglot.com/9-tips-for-designing-a-multi-language-website/

**Comment by marymarywan** [comment]
How many languages Should we have for the website?

**Comment by langsari** [comment]
> How many languages Should we have for the website?

sample by three languages, Thai, English, and Malay and Indonesia but the application design and code to support various.

**Comment by marymarywan** [comment]
### Method and Tool for using
[QuranApplicationLanguage #1.pdf](https://github.com/langsari/the-noble-quran/files/5338957/QuranApplicationLanguage.1.pdf)

**Comment by marymarywan** [comment]
อาจารย์ ผม Pull ไม่ได้ เนื่องจาก There are too many conflicts

**Comment by marymarywan** [comment]
[Basic_Symfony_Translation.pdf](https://github.com/langsari/the-noble-quran/files/5579029/Basic_Symfony_Translation.pdf)

**Comment by langsari** [comment]
> อาจารย์ ผม Pull ไม่ได้ เนื่องจาก There are too many conflicts

 ใช้ branch ของเรา อย่าไปป่นกับ branch อื่น และ อย่าพึ่ง merge แล้วจะ pull ได้
