### ISSUE TITLE
Quran Audio

### ISSUE THREAD

**Issue by langsari** [langsari/the-noble-quran#8]
Collections of Quran audio, 
Recitation, 
play audio, play,
by verse, 
play by surah, 
select Qori, 
play the whole chapter, 
etc.

Feature detail, read, write and describe more in [README.md](https://github.com/langsari/the-noble-quran/blob/master/Modules/QuranAudio/README.md)

Implement in `/Modules/QuranAudio/`

**Comment by Samae99** [comment]
เราจะจบไปด้วยกัน5555


ในวันที่ พ. 16 ก.ย. 2020 เวลา 14:58 MUKHLIS MEERAYA <
notifications@github.com> เขียนว่า:
